# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PremiumMarketingComponentProperties.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)PremiumMarketingComponentProperties.proto\x12\x43\x64iscord_protos.discord_users.v1.PremiumMarketingComponentProperties\"\xb7\t\n#PremiumMarketingComponentProperties\x12\x13\n\x0bplaceholder\x18\x01 \x01(\t\x12\xb3\x01\n\x1c\x61nnouncement_modal_variant_1\x18\x02 \x01(\x0b\x32\x8c\x01.discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.AnnouncementModalVariant1Properties\x1am\n\x0b\x46\x65\x61tureCard\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04pill\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x12\n\nimage_link\x18\x04 \x01(\t\x12\x1e\n\x16image_link_light_theme\x18\x05 \x01(\t\x1a\xb1\x01\n\x12SubscriptionButton\x12\x0c\n\x04\x63opy\x18\x01 \x01(\t\x12\x8c\x01\n\rbutton_action\x18\x02 \x01(\x0e\x32u.discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.ButtonAction\x1a\xc8\x04\n#AnnouncementModalVariant1Properties\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x11\n\tsubheader\x18\x02 \x01(\t\x12\x12\n\nvideo_link\x18\x03 \x01(\t\x12\x17\n\x0fhelp_article_id\x18\x04 \x01(\t\x12\x8b\x01\n\rfeature_cards\x18\x05 \x03(\x0b\x32t.discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.FeatureCard\x12\x90\x01\n\x06\x62utton\x18\x06 \x01(\x0b\x32{.discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.SubscriptionButtonH\x00\x88\x01\x01\x12\x13\n\x0b\x64ismiss_key\x18\x07 \x01(\t\x12\'\n\x1fhero_art_video_link_light_theme\x18\x08 \x01(\t\x12&\n\x1ehero_art_image_link_dark_theme\x18\t \x01(\t\x12\'\n\x1fhero_art_image_link_light_theme\x18\n \x01(\t\x12\x16\n\x0emodal_top_pill\x18\x0b \x01(\tB\t\n\x07_button\"W\n\x0c\x42uttonAction\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x17\n\x13OPEN_MARKETING_PAGE\x10\x01\x12\x1d\n\x19OPEN_TIER_2_PAYMENT_MODAL\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PremiumMarketingComponentProperties_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREMIUMMARKETINGCOMPONENTPROPERTIES._serialized_start=115
  _PREMIUMMARKETINGCOMPONENTPROPERTIES._serialized_end=1322
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_FEATURECARD._serialized_start=357
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_FEATURECARD._serialized_end=466
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_SUBSCRIPTIONBUTTON._serialized_start=469
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_SUBSCRIPTIONBUTTON._serialized_end=646
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_ANNOUNCEMENTMODALVARIANT1PROPERTIES._serialized_start=649
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_ANNOUNCEMENTMODALVARIANT1PROPERTIES._serialized_end=1233
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_BUTTONACTION._serialized_start=1235
  _PREMIUMMARKETINGCOMPONENTPROPERTIES_BUTTONACTION._serialized_end=1322
# @@protoc_insertion_point(module_scope)
