// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "PremiumMarketingComponentProperties.proto" (package "discord_protos.discord_users.v1.PremiumMarketingComponentProperties", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties
 */
export interface PremiumMarketingComponentProperties {
    /**
     * @generated from protobuf field: string placeholder = 1;
     */
    placeholder: string;
    /**
     * @generated from protobuf field: discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.AnnouncementModalVariant1Properties announcement_modal_variant_1 = 2;
     */
    announcementModalVariant1?: PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties;
}
/**
 * @generated from protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.FeatureCard
 */
export interface PremiumMarketingComponentProperties_FeatureCard {
    /**
     * @generated from protobuf field: string header = 1;
     */
    header: string;
    /**
     * @generated from protobuf field: string pill = 2;
     */
    pill: string;
    /**
     * @generated from protobuf field: string body = 3;
     */
    body: string;
    /**
     * @generated from protobuf field: string image_link = 4;
     */
    imageLink: string;
    /**
     * @generated from protobuf field: string image_link_light_theme = 5;
     */
    imageLinkLightTheme: string;
}
/**
 * @generated from protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.SubscriptionButton
 */
export interface PremiumMarketingComponentProperties_SubscriptionButton {
    /**
     * @generated from protobuf field: string copy = 1;
     */
    copy: string;
    /**
     * @generated from protobuf field: discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.ButtonAction button_action = 2;
     */
    buttonAction: PremiumMarketingComponentProperties_ButtonAction;
}
/**
 * @generated from protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.AnnouncementModalVariant1Properties
 */
export interface PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties {
    /**
     * @generated from protobuf field: string header = 1;
     */
    header: string;
    /**
     * @generated from protobuf field: string subheader = 2;
     */
    subheader: string;
    /**
     * @generated from protobuf field: string video_link = 3;
     */
    videoLink: string;
    /**
     * @generated from protobuf field: string help_article_id = 4;
     */
    helpArticleId: string;
    /**
     * @generated from protobuf field: repeated discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.FeatureCard feature_cards = 5;
     */
    featureCards: PremiumMarketingComponentProperties_FeatureCard[];
    /**
     * @generated from protobuf field: optional discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.SubscriptionButton button = 6;
     */
    button?: PremiumMarketingComponentProperties_SubscriptionButton;
    /**
     * @generated from protobuf field: string dismiss_key = 7;
     */
    dismissKey: string;
    /**
     * @generated from protobuf field: string hero_art_video_link_light_theme = 8;
     */
    heroArtVideoLinkLightTheme: string;
    /**
     * @generated from protobuf field: string hero_art_image_link_dark_theme = 9;
     */
    heroArtImageLinkDarkTheme: string;
    /**
     * @generated from protobuf field: string hero_art_image_link_light_theme = 10;
     */
    heroArtImageLinkLightTheme: string;
    /**
     * @generated from protobuf field: string modal_top_pill = 11;
     */
    modalTopPill: string;
}
/**
 * @generated from protobuf enum discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.ButtonAction
 */
export enum PremiumMarketingComponentProperties_ButtonAction {
    /**
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: OPEN_MARKETING_PAGE = 1;
     */
    OPEN_MARKETING_PAGE = 1,
    /**
     * @generated from protobuf enum value: OPEN_TIER_2_PAYMENT_MODAL = 2;
     */
    OPEN_TIER_2_PAYMENT_MODAL = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class PremiumMarketingComponentProperties$Type extends MessageType<PremiumMarketingComponentProperties> {
    constructor() {
        super("discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties", [
            { no: 1, name: "placeholder", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "announcement_modal_variant_1", kind: "message", T: () => PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties }
        ]);
    }
    create(value?: PartialMessage<PremiumMarketingComponentProperties>): PremiumMarketingComponentProperties {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.placeholder = "";
        if (value !== undefined)
            reflectionMergePartial<PremiumMarketingComponentProperties>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PremiumMarketingComponentProperties): PremiumMarketingComponentProperties {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string placeholder */ 1:
                    message.placeholder = reader.string();
                    break;
                case /* discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.AnnouncementModalVariant1Properties announcement_modal_variant_1 */ 2:
                    message.announcementModalVariant1 = PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties.internalBinaryRead(reader, reader.uint32(), options, message.announcementModalVariant1);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PremiumMarketingComponentProperties, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string placeholder = 1; */
        if (message.placeholder !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.placeholder);
        /* discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.AnnouncementModalVariant1Properties announcement_modal_variant_1 = 2; */
        if (message.announcementModalVariant1)
            PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties.internalBinaryWrite(message.announcementModalVariant1, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties
 */
export const PremiumMarketingComponentProperties = new PremiumMarketingComponentProperties$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PremiumMarketingComponentProperties_FeatureCard$Type extends MessageType<PremiumMarketingComponentProperties_FeatureCard> {
    constructor() {
        super("discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.FeatureCard", [
            { no: 1, name: "header", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "pill", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "body", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "image_link", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "image_link_light_theme", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PremiumMarketingComponentProperties_FeatureCard>): PremiumMarketingComponentProperties_FeatureCard {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.header = "";
        message.pill = "";
        message.body = "";
        message.imageLink = "";
        message.imageLinkLightTheme = "";
        if (value !== undefined)
            reflectionMergePartial<PremiumMarketingComponentProperties_FeatureCard>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PremiumMarketingComponentProperties_FeatureCard): PremiumMarketingComponentProperties_FeatureCard {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string header */ 1:
                    message.header = reader.string();
                    break;
                case /* string pill */ 2:
                    message.pill = reader.string();
                    break;
                case /* string body */ 3:
                    message.body = reader.string();
                    break;
                case /* string image_link */ 4:
                    message.imageLink = reader.string();
                    break;
                case /* string image_link_light_theme */ 5:
                    message.imageLinkLightTheme = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PremiumMarketingComponentProperties_FeatureCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string header = 1; */
        if (message.header !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.header);
        /* string pill = 2; */
        if (message.pill !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.pill);
        /* string body = 3; */
        if (message.body !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.body);
        /* string image_link = 4; */
        if (message.imageLink !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.imageLink);
        /* string image_link_light_theme = 5; */
        if (message.imageLinkLightTheme !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.imageLinkLightTheme);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.FeatureCard
 */
export const PremiumMarketingComponentProperties_FeatureCard = new PremiumMarketingComponentProperties_FeatureCard$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PremiumMarketingComponentProperties_SubscriptionButton$Type extends MessageType<PremiumMarketingComponentProperties_SubscriptionButton> {
    constructor() {
        super("discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.SubscriptionButton", [
            { no: 1, name: "copy", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "button_action", kind: "enum", T: () => ["discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.ButtonAction", PremiumMarketingComponentProperties_ButtonAction] }
        ]);
    }
    create(value?: PartialMessage<PremiumMarketingComponentProperties_SubscriptionButton>): PremiumMarketingComponentProperties_SubscriptionButton {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.copy = "";
        message.buttonAction = 0;
        if (value !== undefined)
            reflectionMergePartial<PremiumMarketingComponentProperties_SubscriptionButton>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PremiumMarketingComponentProperties_SubscriptionButton): PremiumMarketingComponentProperties_SubscriptionButton {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string copy */ 1:
                    message.copy = reader.string();
                    break;
                case /* discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.ButtonAction button_action */ 2:
                    message.buttonAction = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PremiumMarketingComponentProperties_SubscriptionButton, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string copy = 1; */
        if (message.copy !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.copy);
        /* discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.ButtonAction button_action = 2; */
        if (message.buttonAction !== 0)
            writer.tag(2, WireType.Varint).int32(message.buttonAction);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.SubscriptionButton
 */
export const PremiumMarketingComponentProperties_SubscriptionButton = new PremiumMarketingComponentProperties_SubscriptionButton$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties$Type extends MessageType<PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties> {
    constructor() {
        super("discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.AnnouncementModalVariant1Properties", [
            { no: 1, name: "header", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "subheader", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "video_link", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "help_article_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "feature_cards", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PremiumMarketingComponentProperties_FeatureCard },
            { no: 6, name: "button", kind: "message", T: () => PremiumMarketingComponentProperties_SubscriptionButton },
            { no: 7, name: "dismiss_key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "hero_art_video_link_light_theme", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "hero_art_image_link_dark_theme", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "hero_art_image_link_light_theme", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "modal_top_pill", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties>): PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.header = "";
        message.subheader = "";
        message.videoLink = "";
        message.helpArticleId = "";
        message.featureCards = [];
        message.dismissKey = "";
        message.heroArtVideoLinkLightTheme = "";
        message.heroArtImageLinkDarkTheme = "";
        message.heroArtImageLinkLightTheme = "";
        message.modalTopPill = "";
        if (value !== undefined)
            reflectionMergePartial<PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties): PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string header */ 1:
                    message.header = reader.string();
                    break;
                case /* string subheader */ 2:
                    message.subheader = reader.string();
                    break;
                case /* string video_link */ 3:
                    message.videoLink = reader.string();
                    break;
                case /* string help_article_id */ 4:
                    message.helpArticleId = reader.string();
                    break;
                case /* repeated discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.FeatureCard feature_cards */ 5:
                    message.featureCards.push(PremiumMarketingComponentProperties_FeatureCard.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.SubscriptionButton button */ 6:
                    message.button = PremiumMarketingComponentProperties_SubscriptionButton.internalBinaryRead(reader, reader.uint32(), options, message.button);
                    break;
                case /* string dismiss_key */ 7:
                    message.dismissKey = reader.string();
                    break;
                case /* string hero_art_video_link_light_theme */ 8:
                    message.heroArtVideoLinkLightTheme = reader.string();
                    break;
                case /* string hero_art_image_link_dark_theme */ 9:
                    message.heroArtImageLinkDarkTheme = reader.string();
                    break;
                case /* string hero_art_image_link_light_theme */ 10:
                    message.heroArtImageLinkLightTheme = reader.string();
                    break;
                case /* string modal_top_pill */ 11:
                    message.modalTopPill = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string header = 1; */
        if (message.header !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.header);
        /* string subheader = 2; */
        if (message.subheader !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.subheader);
        /* string video_link = 3; */
        if (message.videoLink !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.videoLink);
        /* string help_article_id = 4; */
        if (message.helpArticleId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.helpArticleId);
        /* repeated discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.FeatureCard feature_cards = 5; */
        for (let i = 0; i < message.featureCards.length; i++)
            PremiumMarketingComponentProperties_FeatureCard.internalBinaryWrite(message.featureCards[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.SubscriptionButton button = 6; */
        if (message.button)
            PremiumMarketingComponentProperties_SubscriptionButton.internalBinaryWrite(message.button, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* string dismiss_key = 7; */
        if (message.dismissKey !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.dismissKey);
        /* string hero_art_video_link_light_theme = 8; */
        if (message.heroArtVideoLinkLightTheme !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.heroArtVideoLinkLightTheme);
        /* string hero_art_image_link_dark_theme = 9; */
        if (message.heroArtImageLinkDarkTheme !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.heroArtImageLinkDarkTheme);
        /* string hero_art_image_link_light_theme = 10; */
        if (message.heroArtImageLinkLightTheme !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.heroArtImageLinkLightTheme);
        /* string modal_top_pill = 11; */
        if (message.modalTopPill !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.modalTopPill);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_users.v1.PremiumMarketingComponentProperties.PremiumMarketingComponentProperties.AnnouncementModalVariant1Properties
 */
export const PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties = new PremiumMarketingComponentProperties_AnnouncementModalVariant1Properties$Type();
